services:
  api:
    image: llanos1205/soft806-api:latest
    container_name: api
    hostname: api
    ports:
      - "3000:3000"
    depends_on:
      db_sqlserver:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    environment:
      - SEEDING=True
      - DOTNET_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:3000
  db_sqlserver:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: db_sqlserver
    hostname: db_sqlserver
    ports:
      - "5433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password123
    healthcheck:
      test: "exit 0"
  migrations:
    image: mcr.microsoft.com/mssql-tools
    command: /bin/bash
    healthcheck:
      test: "exit 0"
    depends_on:
      db_sqlserver:
        condition: service_healthy
    volumes:
      - ./SQLScripts/base_migration.sql:/init.sql:ro
      - ./SQLScripts/seed_migration.sql:/seed.sql:ro
    entrypoint: >
      bash -c "
      echo 'Waiting for db_sqlserver to be ready...' ;
      /opt/mssql-tools/bin/sqlcmd -S db_sqlserver -U sa -P Password123 -Q 'CREATE DATABASE Soft806;';
      echo 'Database Soft806 created';
      echo 'Waiting for schema to be created...';
      /opt/mssql-tools/bin/sqlcmd -S db_sqlserver -U sa -P Password123 -d Soft806 -i /init.sql;
      echo 'Schema created';
      echo 'Waiting for seed data to be created...';
      /opt/mssql-tools/bin/sqlcmd -S db_sqlserver -U sa -P Password123 -d Soft806 -i /seed.sql;
      echo 'Seed data created';
      echo 'Migration completed';
      "
