services:
  api:
    image: soft806-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    hostname: api
    ports:
      - "3000:3000"
    depends_on:
      db_sqlserver:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    environment:
      - SEEDING=True
      - DOTNET_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:3000
  db_sqlserver:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: db_sqlserver
    hostname: db_sqlserver
    ports:
      - "5433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password123
    healthcheck:
      test: "exit 0"
  migrations:
    image: soft806-migrations:latest
    healthcheck:
      test: "exit 0"
    build:
      context: .
      dockerfile: Migrations.Dockerfile
    depends_on:
      db_sqlserver:
        condition: service_healthy
    environment:
      - DOTNET_ENVIRONMENT=Development
      - SEEDING=False
    entrypoint: [ "dotnet", "ef", "database", "update", "--project", "SOFT806.Infrastructure/SOFT806.Infrastructure.csproj", "--startup-project", "SOFT806.WebApp/SOFT806.WebApp.csproj" ]

