name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build application
        run: dotnet build SOFT703A2.WebApp --configuration Release --no-restore

      - name: Run tests
        run: dotnet test SOFT806.Tests --no-restore --configuration Release --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage
      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: ./coverage/**/coverage.cobertura.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '60 80'
      - name: Publish application
        run: dotnet publish SOFT703A2.WebApp --configuration Release --output ./publish --no-restore  --no-build

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: webapp-artifact
          path: ./publish
  deploy:
    
    runs-on: self-hosted
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run docker compose
        run: docker-compose -f docker-compose.yaml up -d